### ISSUE TITLE
Change the name!

### ISSUE THREAD

**Issue by RohanOpenSource** [dude123studios/AdvancedDeepLearning#1]
I was looking for a Deep Learning repository but all I found was this Advanced Deep Learning repo. I looked at the contents and this isn't advanced Deep learning. It is regular deep learning! stop being a sussy impasta

**Comment by tejaschugh** [comment]
Agreed!!! Dude123Studios is amogus impostor!!!

**Comment by dude123studios** [comment]
i can vouch
